// Static deals that appear on the dashboard
export const staticDeals = [
  {
    id: 1,
    title: "853 S 32nd Street",
    address: "853 S 32nd Street",
    city: "San Diego",
    state: "CA",
    zipCode: "92113",
    location: "San Diego, CA 92113",
    type: "Opportunity Zone",
    propertyType: "Multifamily",
    strategy: "BRRRR",
    investmentStrategy: "BRRRR",
    units: 4,
    isMultiFamily: true,
    price: 1295000,
    downPayment: 647500,
    downPaymentPercent: 50,
    currentCapRate: 3.39,
    capRate: 3.39,
    proFormaCapRate: 5.63,
    monthlyRent: 5905,
    proFormaCashFlow: 1938,
    monthlyCashFlow: 1938,
    rentUpside: 2495,
    status: "active",
    daysOnMarket: 2,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 4,
    bathrooms: 4,
    sqft: 7325,
    yearBuilt: 1950,
    features: ["Promise Zone", "Transit Priority", "ADU Potential"],
    description: "4-unit mixed configuration property in an Opportunity Zone with significant value-add potential.",
    riskLevel: "medium",
    timeframe: "6-12 months",
    cashRequired: 647500,
    totalROI: 42.3,
    isDraft: false,
    listingUrl: "https://www.zillow.com/homedetails/853-S-32nd-St-San-Diego-CA-92113/17029949_zpid/",
    listingSource: "Zillow",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 2,
    title: "4223 Menlo Ave",
    address: "4223 Menlo Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92105",
    location: "San Diego, CA 92105",
    type: "House Hack",
    propertyType: "Single Family",
    strategy: "House Hack",
    investmentStrategy: "House Hack",
    price: 675000,
    downPayment: 23625,
    downPaymentPercent: 3.5,
    capRate: 5.2,
    proFormaCapRate: 6.1,
    monthlyRent: 5500,
    monthlyCashFlow: 1067,
    proFormaCashFlow: 1067,
    status: "active",
    daysOnMarket: 1,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 5,
    bathrooms: 3,
    sqft: 1848,
    yearBuilt: 1940,
    features: ["Separate Entrances", "Parking", "Walkable"],
    description: "5-bedroom house hack with main house + ADU. Live in one, rent the others.",
    riskLevel: "low",
    timeframe: "Immediate",
    cashRequired: 45625,
    totalROI: 28.1,
    isDraft: false,
    listingUrl: "https://www.zillow.com/homedetails/4223-Menlo-Ave-San-Diego-CA-92105/17061899_zpid/",
    listingSource: "Zillow",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 3,
    title: "4738 35th Street",
    address: "4738 35th Street",
    city: "San Diego",
    state: "CA",
    zipCode: "92116",
    location: "San Diego, CA 92116",
    type: "Value-Add Duplex",
    propertyType: "Duplex",
    strategy: "BRRRR",
    investmentStrategy: "BRRRR",
    units: 2,
    isMultiFamily: true,
    price: 1150000,
    downPayment: 287500,
    downPaymentPercent: 25,
    capRate: 3.8,
    proFormaCapRate: 5.4,
    monthlyRent: 5200,
    monthlyCashFlow: 875,
    proFormaCashFlow: 875,
    status: "active",
    daysOnMarket: 0,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1650,
    yearBuilt: 1955,
    features: ["A+ Schools", "Below Market Rents", "Low Crime"],
    description: "Duplex in prime North Park location with 30% rent upside potential.",
    riskLevel: "low",
    timeframe: "3-6 months",
    cashRequired: 287500,
    totalROI: 18.5,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 4,
    title: "3327 Cherokee Ave",
    address: "3327 Cherokee Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92104",
    location: "San Diego, CA 92104",
    type: "Premium Flip",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 895000,
    downPayment: 447500,
    downPaymentPercent: 50,
    arv: 1350000,
    rehabCost: 150000,
    holdingCosts: 45000,
    netProfit: 260000,
    roi: 58.1,
    status: "active",
    daysOnMarket: 0,
    confidence: "medium",
    images: ["/api/placeholder/400/300"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    yearBuilt: 1928,
    features: ["Corner Lot", "Original Hardwood", "Spectacular Views"],
    description: "Spanish-style home in North Park with incredible downtown views. Needs full renovation.",
    riskLevel: "medium",
    timeframe: "6-9 months",
    cashRequired: 597500,
    totalROI: 58.1,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 5,
    title: "1642 Montecito Way",
    address: "1642 Montecito Way",
    city: "Ramona",
    state: "CA",
    zipCode: "92065",
    location: "Ramona, CA 92065",
    type: "Horse Property",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 759900,
    downPayment: 379950,
    downPaymentPercent: 50,
    arv: 1100000,
    rehabCost: 125000,
    holdingCosts: 38000,
    netProfit: 177100,
    roi: 46.6,
    status: "active",
    daysOnMarket: 1,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2652,
    yearBuilt: 1988,
    lotSize: "3.68 acres",
    features: ["Pool/Spa", "Horse Facilities", "RV Parking", "City Views"],
    description: "3.68-acre estate with pool, spa, and horse facilities. Needs updating but solid bones.",
    riskLevel: "medium",
    timeframe: "6-9 months",
    cashRequired: 504950,
    totalROI: 46.6,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 6,
    title: "236 Edgehill Dr",
    address: "236 Edgehill Dr",
    city: "La Mesa",
    state: "CA",
    zipCode: "91941",
    location: "La Mesa, CA 91941",
    type: "Value-Add Multifamily",
    propertyType: "Fourplex",
    strategy: "Buy & Hold",
    investmentStrategy: "Buy & Hold",
    units: 4,
    isMultiFamily: true,
    price: 1495000,
    downPayment: 373750,
    downPaymentPercent: 25,
    capRate: 4.2,
    proFormaCapRate: 5.8,
    monthlyRent: 7200,
    monthlyCashFlow: 1450,
    proFormaCashFlow: 1450,
    status: "active",
    daysOnMarket: 3,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 8,
    bathrooms: 4,
    sqft: 3200,
    yearBuilt: 1972,
    features: ["Recently Renovated Units", "Separate Meters", "Low Maintenance"],
    description: "Turnkey fourplex with recent renovations. Three 2BR/1BA units plus one 1BR/1BA.",
    riskLevel: "low",
    timeframe: "Immediate",
    cashRequired: 373750,
    totalROI: 15.6,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 7,
    title: "1815 3rd Ave",
    address: "1815 3rd Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92101",
    location: "San Diego, CA 92101",
    type: "Downtown High-Rise",
    propertyType: "Condo",
    strategy: "Buy & Hold",
    investmentStrategy: "Buy & Hold",
    price: 875000,
    downPayment: 175000,
    downPaymentPercent: 20,
    monthlyRent: 4500,
    capRate: 3.9,
    monthlyCashFlow: 650,
    proFormaCashFlow: 650,
    status: "active",
    daysOnMarket: 0,
    confidence: "medium",
    images: ["/api/placeholder/400/300"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1250,
    yearBuilt: 2018,
    floor: "27th",
    features: ["City & Bay Views", "Concierge", "Gym/Pool", "High-End Finishes"],
    description: "Luxury 27th floor condo in Banker's Hill. Views of bay, airport, and Coronado Bridge.",
    riskLevel: "low",
    timeframe: "Immediate",
    cashRequired: 175000,
    totalROI: 8.9,
    hoaFees: 850,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 8,
    title: "1130 Myra Ave",
    address: "1130 Myra Ave",
    city: "Chula Vista",
    state: "CA",
    zipCode: "91911",
    location: "Chula Vista, CA 91911",
    type: "ADU Opportunity",
    propertyType: "Single Family",
    strategy: "BRRRR",
    investmentStrategy: "BRRRR",
    price: 695000,
    downPayment: 173750,
    downPaymentPercent: 25,
    capRate: 3.5,
    proFormaCapRate: 6.2,
    monthlyRent: 3200,
    proFormaCashFlow: 850,
    proFormaCashFlow2: 2100,
    status: "active",
    daysOnMarket: 1,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1456,
    yearBuilt: 1962,
    lotSize: "6500 sq ft",
    features: ["Large Lot", "ADU Plans Approved", "New AC"],
    description: "3BR home on 6,500 sq ft lot with approved ADU plans. Projected $2,100/mo cash flow after ADU.",
    riskLevel: "medium",
    timeframe: "6-12 months",
    cashRequired: 273750,
    totalROI: 35.4,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 9,
    title: "1642 Pentuckett Ave",
    address: "1642 Pentuckett Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92104",
    location: "San Diego, CA 92104",
    type: "BRRRR Special",
    propertyType: "Single Family",
    strategy: "BRRRR",
    investmentStrategy: "BRRRR",
    price: 625000,
    downPayment: 125000,
    downPaymentPercent: 20,
    capRate: 2.8,
    proFormaCapRate: 5.2,
    monthlyRent: 2800,
    proFormaCashFlow: 450,
    proFormaCashFlow2: 1225,
    arv: 825000,
    status: "active",
    daysOnMarket: 0,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 2,
    bathrooms: 1,
    sqft: 936,
    yearBuilt: 1941,
    features: ["Under Market Value", "Low Downpayment", "Quick Close"],
    description: "Estate sale priced $200k under market. Needs cosmetic work only. ARV $825k after $35k rehab.",
    riskLevel: "low",
    timeframe: "3-6 months",
    cashRequired: 160000,
    totalROI: 12.5,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 10,
    title: "10116 Lake Ave",
    address: "10116 Lake Ave",
    city: "Tampa",
    state: "FL",
    zipCode: "33619",
    location: "Tampa, FL 33619",
    type: "Mobile Home Park",
    propertyType: "Mobile Home Park",
    strategy: "Buy & Hold",
    investmentStrategy: "Buy & Hold",
    price: 3200000,
    downPayment: 2300000,
    downPaymentPercent: 72,
    pricePerUnit: 106667,
    units: 30,
    currentCapRate: 11,
    capRate: 11,
    monthlyIncome: 36442,
    monthlyNOI: 26211,
    operatingExpenses: 10793,
    cashFlow: 22045,
    monthlyCashFlow: 22045,
    cashOnCashReturn: 11.5,
    sellerFinancing: "5% Years 1-2",
    sellerFinancingAmount: 1000000,
    monthlyPayment: 4166,
    currentAvgRent: 1215,
    marketAvgRent: 1465,
    immediateUpside: 250,
    monthToMonthUnits: 23,
    year1CashFlow: 319740,
    year1CashOnCash: 13.9,
    stabilizedCashFlow: 404532,
    stabilizedCashOnCash: 17.6,
    fiveYearCashFlow: 1900000,
    fiveYearAppreciation: 500000,
    fiveYearProfit: 2400000,
    fiveYearROI: 104,
    status: "active",
    daysOnMarket: 0,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 30,
    bathrooms: 30,
    sqft: 0,
    yearBuilt: null,
    features: ["Seller Financing 5%", "100% Occupied", "$250/unit Below Market", "75% Month-to-Month"],
    description: "30 INDIVIDUAL mobile homes on single-family lots with SELLER FINANCING! All units renovated 2020-2025. Current 14% cash-on-cash grows to 17.6% by year 3. Own the homes AND land - no pad rent issues!",
    riskLevel: "low",
    timeframe: "Long-term",
    cashRequired: 2300000,
    totalROI: 11.5,
    isDraft: false,
    listingUrl: "https://www.loopnet.com/Listing/10116-Lake-Ave-Tampa-FL/29876543/",
    listingSource: "LoopNet",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 11,
    title: "20246 Gist Rd",
    address: "20246 Gist Rd",
    city: "Los Gatos",
    state: "CA",
    zipCode: "95033",
    location: "Los Gatos, CA 95033",
    type: "Premium Mountain Flip",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 899000,
    offerPrice: 950000,
    downPayment: 95000,
    downPaymentPercent: 10,
    arv: 2100000,
    arvPerSqFt: 1064,
    rehabBudget: 275000,
    hardMoneyLoan: 855000,
    totalLoanAmount: 1130000,
    interestRate: 10.45,
    holdingCosts: 95105,
    interestPayments: 67005,
    insuranceUtilitiesTaxes: 28100,
    totalCosts: 1330105,
    netProfit: 674895,
    roi: 710,
    totalROI: 710,
    annualizedROI: 947,
    kitchenRemodel: 65000,
    bathroomRemodel: 45000,
    interiorFinishes: 85000,
    exteriorCurbAppeal: 50000,
    systemsPermits: 30000,
    status: "active",
    daysOnMarket: 0,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1974,
    yearBuilt: null,
    lotSize: "2.2 Acres",
    features: ["2.2 ACRES", "Award-Winning Los Gatos Schools", "Mountain Privacy", "Tech Executive Target"],
    description: "Los Gatos mountain property on 2.2 ACRES! Needs cosmetic updating but sits in Silicon Valley's most desirable area. Comps $974-$1,510/sq ft on lots under 0.5 acres. Conservative ARV targeting $1,064/sq ft.",
    riskLevel: "medium",
    timeframe: "9 months",
    cashRequired: 95000,
    monthlyRent: 0,
    capRate: 0,
    monthlyCashFlow: 0,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 12,
    title: "9638 E St",
    address: "9638 E St",
    city: "Oakland",
    state: "CA",
    zipCode: "94603",
    location: "Oakland, CA 94603",
    type: "HUD Home Flip",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 281000,
    downPayment: 28100,
    downPaymentPercent: 10,
    arv: 725000,
    rehabBudget: 110000,
    totalInvestment: 419100,
    netProfit: 217000,
    roi: 228,
    totalROI: 228,
    annualizedROI: 456,
    status: "active",
    daysOnMarket: 2,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1387,
    yearBuilt: 1955,
    features: ["HUD Home", "10% Down", "Quick Close", "Approved for 203k"],
    description: "HUD foreclosure in Mills Montclair. Priced at $281k with ARV of $725k. Needs full renovation but comps support huge profit margin. Eligible for FHA 203k loan with just 10% down!",
    riskLevel: "medium",
    timeframe: "6 months",
    cashRequired: 138100,
    monthlyRent: 0,
    capRate: 0,
    monthlyCashFlow: 0,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];