// Static deals that appear on the dashboard
export const staticDeals = [
  {
    id: 2,
    title: "4223 Menlo Ave",
    address: "4223 Menlo Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92105",
    location: "San Diego, CA 92105",
    type: "House Hack",
    propertyType: "Single Family",
    strategy: "House Hack",
    investmentStrategy: "House Hack",
    price: 675000,
    downPayment: 23625,
    downPaymentPercent: 3.5,
    capRate: 5.2,
    proFormaCapRate: 6.1,
    monthlyRent: 5500,
    monthlyCashFlow: 1067,
    proFormaCashFlow: 1067,
    status: "active",
    daysOnMarket: 1,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 5,
    bathrooms: 3,
    sqft: 1848,
    yearBuilt: 1940,
    features: ["Separate Entrances", "Parking", "Walkable"],
    description: "5-bedroom house hack with main house + ADU. Live in one, rent the others.",
    riskLevel: "low",
    timeframe: "Immediate",
    cashRequired: 45625,
    totalROI: 28.1,
    isDraft: false,
    listingUrl: "https://www.zillow.com/homedetails/4223-Menlo-Ave-San-Diego-CA-92105/17061899_zpid/",
    listingSource: "Zillow",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 3,
    title: "4738 35th Street",
    address: "4738 35th Street",
    city: "San Diego",
    state: "CA",
    zipCode: "92116",
    location: "San Diego, CA 92116",
    type: "Value-Add Duplex",
    propertyType: "Duplex",
    strategy: "BRRRR",
    investmentStrategy: "BRRRR",
    units: 2,
    isMultiFamily: true,
    price: 1150000,
    downPayment: 287500,
    downPaymentPercent: 25,
    capRate: 3.8,
    proFormaCapRate: 5.4,
    monthlyRent: 5200,
    monthlyCashFlow: 875,
    proFormaCashFlow: 875,
    status: "active",
    daysOnMarket: 0,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1650,
    yearBuilt: 1955,
    features: ["A+ Schools", "Below Market Rents", "Low Crime"],
    description: "Duplex in prime North Park location with 30% rent upside potential.",
    riskLevel: "low",
    timeframe: "3-6 months",
    cashRequired: 287500,
    totalROI: 18.5,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 4,
    title: "3327 Cherokee Ave",
    address: "3327 Cherokee Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92104",
    location: "San Diego, CA 92104",
    type: "Premium Flip",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 895000,
    downPayment: 447500,
    downPaymentPercent: 50,
    arv: 1350000,
    rehabCost: 150000,
    holdingCosts: 45000,
    netProfit: 260000,
    roi: 58.1,
    status: "active",
    daysOnMarket: 0,
    confidence: "medium",
    images: ["/api/placeholder/400/300"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    yearBuilt: 1928,
    features: ["Corner Lot", "Original Hardwood", "Spectacular Views"],
    description: "Spanish-style home in North Park with incredible downtown views. Needs full renovation.",
    riskLevel: "medium",
    timeframe: "6-9 months",
    cashRequired: 597500,
    totalROI: 58.1,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 5,
    title: "1642 Montecito Way",
    address: "1642 Montecito Way",
    city: "Ramona",
    state: "CA",
    zipCode: "92065",
    location: "Ramona, CA 92065",
    type: "Horse Property",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 759900,
    downPayment: 379950,
    downPaymentPercent: 50,
    arv: 1100000,
    rehabCost: 125000,
    holdingCosts: 38000,
    netProfit: 177100,
    roi: 46.6,
    status: "active",
    daysOnMarket: 1,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2652,
    yearBuilt: 1988,
    lotSize: "3.68 acres",
    features: ["Pool/Spa", "Horse Facilities", "RV Parking", "City Views"],
    description: "3.68-acre estate with pool, spa, and horse facilities. Needs updating but solid bones.",
    riskLevel: "medium",
    timeframe: "6-9 months",
    cashRequired: 504950,
    totalROI: 46.6,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 6,
    title: "236 Edgehill Dr",
    address: "236 Edgehill Dr",
    city: "La Mesa",
    state: "CA",
    zipCode: "91941",
    location: "La Mesa, CA 91941",
    type: "Value-Add Multifamily",
    propertyType: "Fourplex",
    strategy: "Buy & Hold",
    investmentStrategy: "Buy & Hold",
    units: 4,
    isMultiFamily: true,
    price: 1495000,
    downPayment: 373750,
    downPaymentPercent: 25,
    capRate: 4.2,
    proFormaCapRate: 5.8,
    monthlyRent: 7200,
    monthlyCashFlow: 1450,
    proFormaCashFlow: 1450,
    status: "active",
    daysOnMarket: 3,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 8,
    bathrooms: 4,
    sqft: 3200,
    yearBuilt: 1972,
    features: ["Recently Renovated Units", "Separate Meters", "Low Maintenance"],
    description: "Turnkey fourplex with recent renovations. Three 2BR/1BA units plus one 1BR/1BA.",
    riskLevel: "low",
    timeframe: "Immediate",
    cashRequired: 373750,
    totalROI: 15.6,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 7,
    title: "1815 3rd Ave",
    address: "1815 3rd Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92101",
    location: "San Diego, CA 92101",
    type: "Downtown High-Rise",
    propertyType: "Condo",
    strategy: "Buy & Hold",
    investmentStrategy: "Buy & Hold",
    price: 875000,
    downPayment: 175000,
    downPaymentPercent: 20,
    monthlyRent: 4500,
    capRate: 3.9,
    monthlyCashFlow: 650,
    proFormaCashFlow: 650,
    status: "active",
    daysOnMarket: 0,
    confidence: "medium",
    images: ["/api/placeholder/400/300"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1250,
    yearBuilt: 2018,
    floor: "27th",
    features: ["City & Bay Views", "Concierge", "Gym/Pool", "High-End Finishes"],
    description: "Luxury 27th floor condo in Banker's Hill. Views of bay, airport, and Coronado Bridge.",
    riskLevel: "low",
    timeframe: "Immediate",
    cashRequired: 175000,
    totalROI: 8.9,
    hoaFees: 850,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 8,
    title: "1130 Myra Ave",
    address: "1130 Myra Ave",
    city: "Chula Vista",
    state: "CA",
    zipCode: "91911",
    location: "Chula Vista, CA 91911",
    type: "ADU Opportunity",
    propertyType: "Single Family",
    strategy: "BRRRR",
    investmentStrategy: "BRRRR",
    price: 695000,
    downPayment: 173750,
    downPaymentPercent: 25,
    capRate: 3.5,
    proFormaCapRate: 6.2,
    monthlyRent: 3200,
    proFormaCashFlow: 850,
    proFormaCashFlow2: 2100,
    status: "active",
    daysOnMarket: 1,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1456,
    yearBuilt: 1962,
    lotSize: "6500 sq ft",
    features: ["Large Lot", "ADU Plans Approved", "New AC"],
    description: "3BR home on 6,500 sq ft lot with approved ADU plans. Projected $2,100/mo cash flow after ADU.",
    riskLevel: "medium",
    timeframe: "6-12 months",
    cashRequired: 273750,
    totalROI: 35.4,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 9,
    title: "1642 Pentuckett Ave",
    address: "1642 Pentuckett Ave",
    city: "San Diego",
    state: "CA",
    zipCode: "92104",
    location: "San Diego, CA 92104",
    type: "BRRRR Special",
    propertyType: "Single Family",
    strategy: "BRRRR",
    investmentStrategy: "BRRRR",
    price: 625000,
    downPayment: 125000,
    downPaymentPercent: 20,
    capRate: 2.8,
    proFormaCapRate: 5.2,
    monthlyRent: 2800,
    proFormaCashFlow: 450,
    proFormaCashFlow2: 1225,
    arv: 825000,
    status: "active",
    daysOnMarket: 0,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 2,
    bathrooms: 1,
    sqft: 936,
    yearBuilt: 1941,
    features: ["Under Market Value", "Low Downpayment", "Quick Close"],
    description: "Estate sale priced $200k under market. Needs cosmetic work only. ARV $825k after $35k rehab.",
    riskLevel: "low",
    timeframe: "3-6 months",
    cashRequired: 160000,
    totalROI: 12.5,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 10,
    title: "10116 Lake Ave",
    address: "10116 Lake Ave",
    city: "Tampa",
    state: "FL",
    zipCode: "33619",
    location: "Tampa, FL 33619",
    type: "Mobile Home Park",
    propertyType: "Mobile Home Park",
    strategy: "Buy & Hold",
    investmentStrategy: "Buy & Hold",
    price: 3200000,
    downPayment: 2300000,
    downPaymentPercent: 72,
    pricePerUnit: 106667,
    units: 30,
    currentCapRate: 11,
    capRate: 11,
    monthlyIncome: 36442,
    monthlyNOI: 26211,
    operatingExpenses: 10793,
    cashFlow: 22045,
    monthlyCashFlow: 22045,
    cashOnCashReturn: 11.5,
    sellerFinancing: "5% Years 1-2",
    sellerFinancingAmount: 1000000,
    monthlyPayment: 4166,
    currentAvgRent: 1215,
    marketAvgRent: 1465,
    immediateUpside: 250,
    monthToMonthUnits: 23,
    year1CashFlow: 319740,
    year1CashOnCash: 13.9,
    stabilizedCashFlow: 404532,
    stabilizedCashOnCash: 17.6,
    fiveYearCashFlow: 1900000,
    fiveYearAppreciation: 500000,
    fiveYearProfit: 2400000,
    fiveYearROI: 104,
    status: "active",
    daysOnMarket: 0,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 30,
    bathrooms: 30,
    sqft: 0,
    yearBuilt: null,
    features: ["Seller Financing 5%", "100% Occupied", "$250/unit Below Market", "75% Month-to-Month"],
    description: "30 INDIVIDUAL mobile homes on single-family lots with SELLER FINANCING! All units renovated 2020-2025. Current 14% cash-on-cash grows to 17.6% by year 3. Own the homes AND land - no pad rent issues!",
    riskLevel: "low",
    timeframe: "Long-term",
    cashRequired: 2300000,
    totalROI: 11.5,
    isDraft: false,
    listingUrl: "https://www.loopnet.com/Listing/10116-Lake-Ave-Tampa-FL/29876543/",
    listingSource: "LoopNet",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 11,
    title: "20246 Gist Rd",
    address: "20246 Gist Rd",
    city: "Los Gatos",
    state: "CA",
    zipCode: "95033",
    location: "Los Gatos, CA 95033",
    type: "Premium Mountain Flip",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 899000,
    offerPrice: 950000,
    downPayment: 95000,
    downPaymentPercent: 10,
    arv: 2100000,
    arvPerSqFt: 1064,
    rehabBudget: 275000,
    hardMoneyLoan: 855000,
    totalLoanAmount: 1130000,
    interestRate: 10.45,
    holdingCosts: 95105,
    interestPayments: 67005,
    insuranceUtilitiesTaxes: 28100,
    totalCosts: 1330105,
    netProfit: 674895,
    roi: 710,
    totalROI: 710,
    annualizedROI: 947,
    kitchenRemodel: 65000,
    bathroomRemodel: 45000,
    interiorFinishes: 85000,
    exteriorCurbAppeal: 50000,
    systemsPermits: 30000,
    status: "active",
    daysOnMarket: 0,
    confidence: "high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1974,
    yearBuilt: null,
    lotSize: "2.2 Acres",
    features: ["2.2 ACRES", "Award-Winning Los Gatos Schools", "Mountain Privacy", "Tech Executive Target"],
    description: "Los Gatos mountain property on 2.2 ACRES! Needs cosmetic updating but sits in Silicon Valley's most desirable area. Comps $974-$1,510/sq ft on lots under 0.5 acres. Conservative ARV targeting $1,064/sq ft.",
    riskLevel: "medium",
    timeframe: "9 months",
    cashRequired: 95000,
    monthlyRent: 0,
    capRate: 0,
    monthlyCashFlow: 0,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 12,
    title: "9638 E St",
    address: "9638 E St",
    city: "Oakland",
    state: "CA",
    zipCode: "94603",
    location: "Oakland, CA 94603",
    type: "HUD Home Flip",
    propertyType: "Single Family",
    strategy: "Fix & Flip",
    investmentStrategy: "Fix & Flip",
    price: 281000,
    downPayment: 28100,
    downPaymentPercent: 10,
    arv: 725000,
    rehabBudget: 110000,
    totalInvestment: 419100,
    netProfit: 217000,
    roi: 228,
    totalROI: 228,
    annualizedROI: 456,
    status: "active",
    daysOnMarket: 2,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1387,
    yearBuilt: 1955,
    features: ["HUD Home", "10% Down", "Quick Close", "Approved for 203k"],
    description: "HUD foreclosure in Mills Montclair. Priced at $281k with ARV of $725k. Needs full renovation but comps support huge profit margin. Eligible for FHA 203k loan with just 10% down!",
    riskLevel: "medium",
    timeframe: "6 months",
    cashRequired: 138100,
    monthlyRent: 0,
    capRate: 0,
    monthlyCashFlow: 0,
    isDraft: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 15,
    title: "Napa 3-Unit House Hack - Live in Wine Country Paradise!",
    address: "850 Caymus St",
    city: "Napa",
    state: "CA",
    zipCode: "94559",
    location: "Napa, CA 94559",
    type: "House Hack",
    propertyType: "Multi-Family",
    strategy: "House Hack - Live Free in Wine Country",
    investmentStrategy: "House Hack",
    units: 3,
    isMultiFamily: true,
    price: 825000,
    downPayment: 28875,
    downPaymentPercent: 3.5,
    currentCapRate: 6.1,
    capRate: 6.1,
    proFormaCapRate: 9.8,
    monthlyRent: 5600,
    projectedRent: 8100,
    proFormaCashFlow: 1260,
    monthlyCashFlow: -1240,
    rentUpside: 2500,
    status: "active",
    daysOnMarket: 0,
    confidence: "very high",
    images: ["/api/placeholder/400/300"],
    bedrooms: 5,
    bathrooms: 3,
    sqft: 2800,
    yearBuilt: 1880,
    features: [
      "Two Buildings on One Lot",
      "Warehouse with ADU Potential", 
      "5 Blocks from Downtown Napa",
      "3BR Main House + 2 Studios",
      "FHA Eligible - 3.5% Down",
      "Wine Country Premium Location",
      "Multiple Income Streams",
      "Walk to Restaurants & Wine Tasting",
      "Event Hosting Potential",
      "$2,500/mo Warehouse ADU Opportunity"
    ],
    description: "Incredible house hack in downtown Napa! Two buildings on one lot with warehouse bonus. Live in a studio while collecting $5,600/month from the main house and other studio. Just 5 blocks from downtown Napa. After warehouse ADU conversion, you'll GET PAID $1,260/month to live in wine country!",
    riskLevel: "low",
    timeframe: "immediate",
    cashRequired: 45375,
    totalROI: 190.0,  // 1900% expressed as decimal (matches other properties format)
    isDraft: false,
    listingUrl: "https://www.loopnet.com/Listing/850-Caymus-St-Napa-CA/37220526/",
    listingSource: "LoopNet",
    
    // Financial Details
    interestRate: 6.75,
    loanTerm: 30,
    monthlyPI: 5166,
    monthlyMIP: 564,
    closingCosts: 16500,
    rehabCosts: 100000,
    rehabDetails: {
      "Warehouse to ADU Conversion": 100000,
      "Move-in Ready": 0
    },
    propertyTaxes: 860,
    insurance: 250,
    hoa: 0,
    hoaFees: 0,
    utilities: 0,
    maintenance: 200,
    propertyManagement: 0,
    vacancy: 280,
    capitalExpenditures: 200,
    
    // Neighborhood & Location
    neighborhoodClass: "A",
    neighborhood: "Downtown Napa",
    lotSize: "0.25 acres",
    walkScore: 85,
    
    // Rental Analysis
    currentRent: 5600,
    cashOnCashReturn: -5.14,  // -51.4% expressed as decimal
    
    // Premium Newsletter Sections
    strategicOverview: `This is a rare house hack opportunity in the heart of Napa Valley. With just $28,875 down using an FHA loan, you can control a property with three income-producing units plus a warehouse with massive potential. Live in one studio while renting the main house and other studio for $5,600/month, covering most of your housing costs. Your net cost is only $1,240/month - cheaper than renting! The real opportunity lies in the warehouse conversion - add an ADU for $100k and you'll actually GET PAID $1,260/month to live in downtown Napa. Located just 5 blocks from downtown with restaurants, wine tasting rooms, and Oxbow Market. The 5-year projection shows $550,000 total return on your $28,875 investment - a 1,900% ROI!`,
    
    valueAddDescription: `The warehouse conversion is the hidden goldmine. For $100k (financeable through HELOC after year 1), convert to a legal ADU renting for $2,500/month. Additional value-adds: Weekend Airbnb arbitrage ($300/night), wine country event hosting ($1,000+ per event), commercial warehouse rental to winemakers ($1,500/month), or wine storage business ($2,000/month). The two-building configuration provides incredible flexibility for various income strategies.`,
    
    locationAnalysis: {
      neighborhood: "Downtown Napa",
      walkScore: 85,
      transitScore: 35,
      bikeScore: 75,
      proximityToDowntown: "5 blocks",
      proximityToHighway: "2 miles to Highway 29",
      nearbyEmployers: [
        { name: "Wine Industry", distance: "Throughout valley", employees: "45,000+" },
        { name: "Queen of the Valley Hospital", distance: "1.5 miles", employees: "2,000+" },
        { name: "Napa Valley College", distance: "3 miles", employees: "500+" }
      ],
      publicTransit: {
        busLines: ["Vine Transit Route 10", "Route 11"],
        nearestStop: "0.3 miles",
        commuteOptions: "San Francisco Ferry (Vallejo) 30 min drive"
      },
      schools: {
        elementary: "Shearer Elementary - 7/10 rating",
        middle: "Silverado Middle - 6/10 rating",
        high: "Napa High - 7/10 rating",
        district: "Napa Valley USD"
      },
      shopping: [
        { name: "Oxbow Public Market", distance: "0.5 miles", type: "Gourmet food hall" },
        { name: "First Street Napa", distance: "0.4 miles", type: "Shopping & dining" },
        { name: "Whole Foods", distance: "1.2 miles", type: "Grocery" }
      ],
      amenities: [
        "Downtown restaurants & cafes",
        "Wine tasting rooms",
        "Napa Valley Wine Train",
        "Napa River Trail",
        "Premium shopping & dining"
      ],
      demographics: {
        population: 79246,
        medianAge: 40.2,
        medianIncome: 92000,
        collegeEducated: 38,
        ownerOccupied: 58
      },
      crimeRate: "Below state average",
      futureDeveopment: "Limited due to agricultural preserve",
      appreciationHistory: "5-7% annual average last 10 years",
      marketTrends: "Limited housing supply, high demand, wine country premium"
    },
    
    rentAnalysis: {
      currentRents: {
        "Main House (3BR/2BA)": 3200,
        "Studio #1": 2400,
        "Studio #2 (Owner Occupied)": 0,
        "Warehouse": 0
      },
      marketRents: {
        "Main House": 3200,
        "Studio": 2400,
        "Warehouse ADU": 2500,
        "Airbnb Weekend": 300
      },
      rentalDemand: "Very High",
      vacancyRate: 3,
      rentGrowth: "4-5% annually",
      rentGrowthRate: 4,
      comparableRents: [
        { address: "Similar 3BR Napa", rent: 3300, sqft: 1600 },
        { address: "Studio Downtown", rent: 2200, sqft: 500 },
        { address: "2BR Unit Nearby", rent: 2800, sqft: 900 }
      ],
      totalUnits: 3,
      currentOccupancy: 100
    },
    
    propertyMetrics: {
      pricePerUnit: 275000,
      pricePerSqFt: 295,
      grossRentMultiplier: 12.3,
      debtServiceCoverageRatio: 0.82,
      breakEvenOccupancy: 92,
      internalRateOfReturn: 38,
      equityMultiple: 19.0,
      paybackPeriod: 2.6
    },
    
    financingScenarios: [
      {
        name: "FHA 3.5% Down (Best for House Hack)",
        downPayment: 28875,
        loanAmount: 796125,
        rate: 6.75,
        monthlyPayment: 5730,
        cashFlow: -1240,
        totalCashNeeded: 45375,
        cashOnCashReturn: -32.8,
        totalROI: 190.0,
        note: "Live almost free in Napa Valley!"
      },
      {
        name: "Conventional 5% Down",
        downPayment: 41250,
        loanAmount: 783750,
        rate: 7.25,
        monthlyPayment: 5544,
        cashFlow: -1004,
        totalCashNeeded: 57750,
        cashOnCashReturn: -20.9,
        totalROI: 175.0
      },
      {
        name: "Conventional 20% Down",
        downPayment: 165000,
        loanAmount: 660000,
        rate: 7.0,
        monthlyPayment: 4391,
        cashFlow: 169,
        totalCashNeeded: 181500,
        cashOnCashReturn: 1.1,
        totalROI: 95.0,
        note: "Positive cash flow from day 1"
      }
    ],
    
    thirtyYearProjections: {
      assumptions: {
        rentGrowthRate: 3,
        expenseGrowthRate: 2.5,
        appreciationRate: 5,
        vacancyRate: 5,
        managementFee: 0,
        maintenanceRate: 5,
        capExRate: 5
      },
      projections: [
        { year: 1, annualCashFlow: -14880, cumulativeCashFlow: -14880, propertyValue: 866250, equity: 69125, loanBalance: 797125, totalROI: -32.8 },
        { year: 2, annualCashFlow: 15120, cumulativeCashFlow: 255, propertyValue: 909563, equity: 212438, loanBalance: 697125, totalROI: 33.4, note: "Warehouse ADU complete" },
        { year: 3, annualCashFlow: 15876, cumulativeCashFlow: 16131, propertyValue: 955041, equity: 259916, loanBalance: 695125, totalROI: 55.5 },
        { year: 5, annualCashFlow: 17500, cumulativeCashFlow: 51631, propertyValue: 1052622, equity: 361497, loanBalance: 691125, totalROI: 113.8 },
        { year: 10, annualCashFlow: 22750, cumulativeCashFlow: 165381, propertyValue: 1344589, equity: 668464, loanBalance: 676125, totalROI: 364.2 },
        { year: 20, annualCashFlow: 36400, cumulativeCashFlow: 455381, propertyValue: 2194481, equity: 1568356, loanBalance: 626125, totalROI: 1584.2 },
        { year: 30, annualCashFlow: 58240, cumulativeCashFlow: 925381, propertyValue: 3569906, equity: 3569906, loanBalance: 0, totalROI: 3204.9 }
      ],
      totalRentalIncome: 2016000,
      totalCashFlow: 925381,
      principalPaydown: 796125,
      propertyAppreciation: 2744906,
      totalReturn: 4466412,
      averageAnnualReturn: 148880,
      totalROI: 883.0,
      equityAtYear30: 3569906
    },
    
    marketAnalysis: {
      comparables: [
        { address: "Similar 3-unit Napa", price: 950000, sqft: 2600, pricePerSqFt: 365, soldDate: "2 months ago" },
        { address: "Downtown duplex", price: 750000, sqft: 2000, pricePerSqFt: 375, soldDate: "1 month ago" },
        { address: "4-plex nearby", price: 1100000, sqft: 3200, pricePerSqFt: 344, soldDate: "3 months ago" }
      ],
      medianPrice: 825000,
      medianPricePerSqFt: 361,
      priceGrowth: 7,
      priceGrowthYoY: "7% Year over Year",
      daysOnMarket: 25,
      averageDaysOnMarket: 28,
      inventoryLevel: "0.8 months supply",
      inventoryTrend: "Declining",
      buyerDemand: "Very High",
      sellerMarket: true,
      sellerConcessions: "Rare in this market",
      marketTemperature: "Hot",
      seasonality: "Peak season spring/summer",
      economicFactors: [
        "Wine tourism driving demand",
        "Tech worker migration from Bay Area",
        "Limited new construction",
        "Agricultural preserve restricts development"
      ],
      forecast: "Continued appreciation 5-7% annually",
      investmentGrade: "A"
    },
    
    rehabAnalysis: {
      immediate: {
        scope: "Move-in ready",
        items: [],
        cost: 0,
        timeline: "Immediate"
      },
      phase1: {
        scope: "Warehouse Planning",
        items: [
          { item: "Architectural plans", cost: 8000 },
          { item: "Permits & approvals", cost: 7000 }
        ],
        cost: 15000,
        timeline: "6 months",
        roi: "N/A - Planning phase"
      },
      phase2: {
        scope: "Warehouse to ADU Conversion",
        items: [
          { item: "Framing & structure", cost: 25000 },
          { item: "Plumbing & electrical", cost: 30000 },
          { item: "Kitchen & bath", cost: 25000 },
          { item: "Finishes & flooring", cost: 20000 }
        ],
        cost: 100000,
        timeline: "4-6 months",
        roi: "30% cash-on-cash return",
        monthlyRentIncrease: 2500
      },
      phase3: {
        scope: "Amenity Upgrades",
        items: [
          { item: "Landscape design", cost: 25000 },
          { item: "Event space setup", cost: 15000 }
        ],
        cost: 40000,
        timeline: "Year 3",
        roi: "Event income $1000+/event"
      },
      totalBudget: 155000,
      postRehabValue: 1100000,
      valueAdd: 275000,
      rehabROI: 177
    },
    
    createdAt: new Date(),
    updatedAt: new Date()
  }
];